Traceback (most recent call last):
  File "main.py", line 80, in <module>
    main(args)
  File "main.py", line 16, in main
    solver = Solver(args)
  File "/home/jeongeun/MLN_XRobust/core/solver.py", line 32, in __init__
    wandb.config.upate({'ratio1':args.ratio,"ratio2":args.ratio2})
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 151, in __getattr__
    return self.__getitem__(key)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 122, in __getitem__
    return self._items[key]
KeyError: 'upate'